# Configuração Geral do Projeto
project_name: "TCC_Modelo_TensorFlow_SWM"
log_file: "logs/app.log"

# Configuração dos Dados
data:
  image_size: [256, 256]
  batch_size: 64
  color_mode: "rgb"

# Configuração do Modelo
model:
  input_shape: [256, 256, 3] # Altura, Largura, Canais
  num_classes: 4 # Número de classes

# Configuração da Previsão
# Mapeamento de índice para nome de classe
prediction:
  class_names: ["caixa_de_papelao", "garrafa", "lata", "tenis"]